apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: sulav
      automountServiceAccountToken: false
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: pvc
      containers:
        - name: database-container
          image: sulavadk7/database_image
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /app/data
              name: database-volume
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432