apiVersion: v1
kind: ServiceAccount
metadata:
  name: sulav
  namespace: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "configmaps"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role
  namespace: development
subjects:
  - kind: ServiceAccount
    name: sulav
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io