version: '3.8'

services:
  database:
    image: postgres_image
    container_name: pdatabase_container
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./database/.env
    networks:
      - network-B-D
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    image: backend_image
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - network-B-D
    depends_on:
      - database
    volumes:
      - ./backend:/app
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 200s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    image: frontend_image
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - network-B-D
    volumes:
      - ./frontend:/app

networks:
  network-B-D:
    driver: bridge

volumes:
  database: {}

  
